### ISSUE TITLE
Possibility to run this application on various systems

### ISSUE THREAD

**Issue by schmunk42** [samdark/intl-icu-data-tables#5]
This extension would be even more helpful, if we could easily run it on top of different PHP/ICU versions, to find out if ie. a formatting has changed.

Related to 
- https://github.com/yiisoft/yii2/issues/15140
- https://github.com/yiisoft/yii2/pull/15518

**Comment by samdark** [comment]
It's not an extension. It's an application. Are there any specific issues that prevent you to run it on particular system?

**Comment by schmunk42** [comment]
I thought about a PR which enables you to use it on top of different systems via Docker.
Would that be OK? 

Won't be able to do it soon, but maybe the next time I start debugging tests ;)

**Comment by samdark** [comment]
I'm not going to host it. That's 5$ DigitalOcean server that hosts about 10 projects :)

**Comment by samdark** [comment]
But yeah, I don't mind merging it.
